services:
  caldav-frontend:
    image: ghcr.io/fuzzymistborn/caldav-frontend:latest
    container_name: caldav-frontend
    ports:
      - "5000:5000"
    environment:
      - CALDAV_SERVER_URL=https://calendar.example.com
      - CALDAV_SERVER_TYPE=nextcloud  # Options: nextcloud, baikal, radicale, generic
      - SECRET_KEY=YOUR_TOKEN  # Generate with `openssl rand -hex 32` or `python3 -c "import secrets; print(secrets.token_urlsafe(32))"`
      - FLASK_ENV=production
      - LOG_LEVEL=info
      - PORT=5000
      # Session Configuration
      - SESSION_LIFETIME_DAYS=7
    volumes:
      - YOURPATH/docker/caldav:/app/data  # Optional: for logs or future use
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s